{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # AWS ALB ingress controller annotations
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/scheme" }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/target-type" }}
    alb.ingress.kubernetes.io/success-code: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/success-code" }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}

