apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-demo-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-demo-blue
  template:
    metadata:
      labels:
        app: sample-demo-blue
    spec:
      containers:
      - name: sample-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

