apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-demo-green-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-demo-green
  minReplicas: 2
  maxReplicas: 5  # Maximum number of replicas to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageUtilization
          averageUtilization: 80  # Scale when CPU utilization is above 800%

